plugin:
    name: 'blskye.curdtools::lang.plugin.name'
    description: 'blskye.curdtools::lang.plugin.description'
    author: Blskye
    icon: oc-icon-outdent
    homepage: ''
permissions:
    blskye.curdtools.manage:
        tab: 'blskye.curdtools::lang.manage'
        label: 'blskye.curdtools::lang.manage'
