plugin:
    name: 'blskye.curdtools::lang.plugin.name'
    description: 'blskye.curdtools::lang.plugin.description'
    author: Blskye
    icon: oc-icon-outdent
    homepage: ''
permissions:
    blskye.curdtools.manage:
        tab: 'blskye.curdtools::lang.manage'
        label: 'blskye.curdtools::lang.manage'
navigation:
    main-menu-item:
        label: 'blskye.curdtools::lang.manage'
        url: blskye/curdtools/curdtoolsdata
        icon: icon-life-ring
        sideMenu:
            side-menu-item:
                label: 'blskye.curdtools::lang.generator_all'
                url: blskye/curdtools/curdtoolsdata
                icon: icon-sitemap
